[[pages]]
path = "pages/welcome.py"
name = "Welcome"
icon = "ğŸ "

[[pages]]
name = "Personal Finance"
icon = ""#ğŸª™
is_section = true

[[pages]]
path = "pages/emergency_fund.py"
name = "Emergency Fund"
icon = "ğŸ’°"

[[pages]]
path = "pages/long_term_forecast.py"
name = "Long Term Forecast"
icon = "ğŸ”­"

[[pages]]
path = "pages/postponement_consequences.py"
name = "Postponement"
icon = "ğŸ–ï¸"
[[pages]]
name = "Investments Data"
icon = ""#ğŸ“ˆ
is_section = true

[[pages]]
path = "pages/correlations.py"
name = "Correlations"
icon = "ğŸ§®"

[[pages]]
path = "pages/mortgage.py"
name = "Mortgage"
icon = "ğŸ¦" 

[[pages]]
name = ""#Coming Soon
icon = "ğŸ”œ"#
is_section = true

[[pages]]
path = "pages/historical_analysis.py"
name = "Historical Analysis"
icon = "ğŸ“Š" 

[[pages]]
path = "pages/etfs_and_leverage.py"
name = "ETFs and Leverage"
icon = "ğŸ“‘" 

[[pages]]
path = "pages/trades_analysis.py"
name = "Trades Analysis"
icon = "ğŸª™" 
